steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME}", "."]
  # Docker push to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}"]
  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_IMAGE_NAME}",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

# 今回は30分にしてみる
timeout: "1800s"

# ユーザー定義変数
substitutions:
  _SERVICE_NAME: "hello-world"
  _IMAGE_NAME: "asia-northeast1-docker.pkg.dev/ca-saki-tomita-test/ca-sakitomi-todo-repo/test-image-0119:test"

images:
  - "${_IMAGE_NAME}"